### PR TITLE
Torchvision dep to test requirements

### PR DESCRIPTION
**Pull request by orangetoaster**
## Summary:
  This is to reduce dependencies for projects that use baal for non-vision applications.

```
% pip install -e .\[test\]
[...]
  Running setup.py develop for baal
Successfully installed baal-1.3.0 [...] torchvision-0.10.0
```

### CODE REVIEW

**Comment by Dref360** [comment]
Oh we duplicate the test requirements in https://github.com/ElementAI/baal/blob/master/test-requirements.txt

Could you merge/add it there too?

**Review by parmidaatg — COMMENTED** [review]
where do we install torchvision now? i dont find it in extras ?

**Comment by parmidaatg** [comment]
> It's currently in `requirements.txt`, to always be installed.

oh yeah I know, but I thought that i should see it in extras in your PR. My question is could you refer me to the line that u moved it to? I cannot find it ?

**Review by parmidaatg — APPROVED** [review]
awesome thanks :)

**Pull request merged**
